---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by digitsu.

function ends_in_3(num) 
  return num % 10 == 3
end

function is_prime(num)
  local gd = 1
  repeat
    gd = gd + 1
    until num % gd == 0
  if gd == num then
    return true
  else
    return false 
  end
end

function first_n_primes_ends_in_3(n)
  local count = 0
  local found = 0

  repeat
    count = count + 1
    if ends_in_3(count) and is_prime(count) then
       found = found + 1
       print( count )
    end
  until found == n
end

function fnp3(n, num)
  if n <= 0 then
    return
  elseif num == nil then
    num = 0
  end

  if ends_in_3(num) and is_prime(num) then
    print(num)
    fnp3(n-1, num + 1)
  else
    fnp3(n, num + 1)
  end
end

function for_loop(a, b, f) 
  while a <= b do
    f(a)
    a = a + 1
  end
end

function add(prev, next)
  return prev + next
end

function mult(x,y)
  return x * y
end


function reduce(max, init, f)
  if init == nil then
    init = 0
  end

  if max <= 1 then
    return f(init, 1)
  else 
    return f( reduce(max-1, init, f), max)
  end
end

function factorial(n)
  if n == 0 then
    return 1
  elseif n > 0 then
    return n * factorial(n-1)
  end
end

function fact(n)
  return reduce(n, 1, mult)
end

